# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K1yGlUyBeTjM21g9GBiISmHiTHxWpz52
"""

#pip install nltk

#pip install newspaper3k

from newspaper import Article
import random
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
#import warnings
#warnings.filterwarnings('ignore')

nltk.download('punkt')
lista = ['https://www.english-at-home.com/conversations-restaurant/','https://7esl.com/restaurant-english/','https://www.fluentu.com/blog/english/restaurant-english-conversation/']
for list in lista:
    first_article = Article(url="%s" % list, language='de')
    first_article.download()
    first_article.parse()
    first_article.nlp
    corpus= article.text
    #print(corpus)

text = corpus
sentence_list = nltk.sent_tokenize(text)
#print(sentence_list)



def greeting_response(text):
  text = text.lower()
  bot_greetings=['Hello','Hi','Hey there','Hola','Good Morning','Welcome','How can I help?']
  user_greetings=['Hey','Hello','What can you do ?','Greetings','Need help']
  for word in text.split():
    if word in user_greetings:
      return random.choice(bot_greetings)

def index_sort(list_var):
  length=len(list_var)
  list_index=list(range(0,length))
  x=list_var
  for i in range(length):
    for j in range(length):
      if x[list_index[i]]>x[list_index[j]]:
        x[list_index[i]],x[list_index[j]]=x[list_index[j]],x[list_index[i]]

def bot_response(user_input):
  user_input = user_input.lower()
  sentence_list.append(user_input)
  bot_response=''
  cm = CountVectorizer().fit_transform(sentence_list)
  similarity_score= cosine_similarity(cm[-1],cm)
  similarity_score_list=similarity_score.flatten()
  index=index_sort(similarity_score_list)
  index = index[1:]
  response_flag=0
  j=0
  for i in range(len(index)):
    if similarity_score_list[index[i]]>0.0:
      bot_response=bot_response+sentence_list[index[i]]
      response_flag=1
      j+=1
    if j>2:
      break
  if response_flag==0:
    bot_response=bot_response+' '+"I am sorry"
  sentence_list.remove(user_input)

print('I am a restaurant bot. I will answer your queries')
exit_list=['exit','see you later','bye','quit','break']
while (True):
  user_input=input()
  if user_input.lower() in exit_list:
    print('Nice meeting you talk to you later!')
    break
  else:
    if greeting_response(user_input)!= None:
      print('Restaurant Bot:' + greeting_response(user_input))
    else:
      print('Restaurant bot'+ bot_response(user_input))
